-- src/main/resources/schema.sql

CREATE TABLE flight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(255) NOT NULL,
    origin VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL
);

CREATE TABLE schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    flight_id BIGINT,
    FOREIGN KEY (flight_id) REFERENCES flight(id)
);

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_name VARCHAR(255) NOT NULL,
    seat_number VARCHAR(255) NOT NULL,
    schedule_id BIGINT,
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);